# Generated by Django 6.0.1 on 2026-01-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('light', 'Light'), ('fan', 'Fan'), ('door', 'Door'), ('ac', 'AC')], max_length=50)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('passcode', models.CharField(blank=True, max_length=50, null=True)),
                ('mqtt_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('id_home', models.ForeignKey(blank=True, db_column='id_home', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homes.home')),
            ],
            options={
                'db_table': 'device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tahc',
            fields=[
                ('id_tahc', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('hum', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('id_home', models.ForeignKey(blank=True, db_column='id_home', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homes.home')),
            ],
            options={
                'db_table': 'tahc',
                'managed': True,
            },
        ),
    ]
