# Generated by Django 6.0.1 on 2026-01-24 09:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FaceUser',
            fields=[
                ('id_face', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vector_image', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True)),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.account')),
            ],
            options={
                'db_table': 'face_user',
                'managed': True,
            },
        ),
    ]
