# Generated by Django 6.0.1 on 2026-01-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('namehome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'home',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HomeUser',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'Member')], default='user', max_length=20)),
                ('id_home', models.ForeignKey(blank=True, db_column='id_home', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homes.home')),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.account')),
            ],
            options={
                'db_table': 'home_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id_request', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('id_home', models.ForeignKey(blank=True, db_column='id_home', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homes.home')),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.account')),
            ],
            options={
                'db_table': 'request',
                'managed': True,
            },
        ),
    ]
