# Generated by Django 6.0.1 on 2026-01-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogHome',
            fields=[
                ('id_loghome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('log_time', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('method', models.CharField(blank=True, choices=[('face_recognition', 'Face Recognition'), ('passcode', 'Passcode'), ('remote_app', 'Remote App')], max_length=50, null=True)),
                ('id_home', models.ForeignKey(blank=True, db_column='id_home', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homes.home')),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.account')),
            ],
            options={
                'db_table': 'log_home',
                'managed': True,
            },
        ),
    ]
